In [1]:
import pandas as pd
import numpy as np

In [16]:

df = pd.read_csv('../data/Personal_Finance_Dataset.csv')

df.head()
# df.tail()
# print(df.columns)
# print(df.shape)
# print(df.shape[0])
# print(df.shape[1])

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense

In [17]:
print(df.columns)

Index(['Date', 'Transaction Description', 'Category', 'Amount', 'Type'], dtype='object')

In [19]:
df.isnull().sum()

Date                       0
Transaction Description    0
Category                   0
Amount                     0
Type                       0
dtype: int64

In [20]:
df.isnull().any()

Date                       False
Transaction Description    False
Category                   False
Amount                     False
Type                       False
dtype: bool

In [21]:
df.isnull().axis = 1

In [22]:
df.isnull().axis = 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1500 non-null   object
 1   Transaction Description  1500 non-null   object
 2   Category                 1500 non-null   object
 3   Amount                   1500 non-null   float64
 4   Type                     1500 non-null   object
dtypes: float64(1), object(4)
memory usage: 58.7+ KB

In [25]:
df['Date'] = pd.to_datetime(df['Date'])

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1500 non-null   datetime64[ns]
 1   Transaction Description  1500 non-null   object
 2   Category                 1500 non-null   object
 3   Amount                   1500 non-null   float64
 4   Type                     1500 non-null   object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 58.7+ KB

In [27]:
print(df.duplicated().sum())

0

In [28]:
print(df['Transaction Description'].unique())

['Score each.' 'Quality throughout.' 'Instead ahead despite measure ago.'
 ... 'No couple debate must.' 'Discussion black follow.'
 'Pressure activity defense detail.']

In [29]:
print(df['Type'].unique())

['Expense' 'Income']

In [30]:
print(df['Category'].unique())

['Food & Drink' 'Utilities' 'Rent' 'Investment' 'Shopping' 'Other'
 'Entertainment' 'Health & Fitness' 'Salary' 'Travel']

In [32]:
print(df['Category'].value_counts())

Category
Rent                165
Travel              160
Utilities           157
Health & Fitness    152
Shopping            150
Food & Drink        149
Salary              146
Entertainment       143
Investment          142
Other               136
Name: count, dtype: int64

In [33]:
print(df.groupby('Category')['Amount'].sum())

Category
Entertainment       148165.47
Food & Drink        159493.39
Health & Fitness    145194.06
Investment          363252.00
Other               370835.00
Rent                162075.39
Salary              149053.55
Shopping            146880.75
Travel              169497.79
Utilities           146833.97
Name: Amount, dtype: float64

In [34]:
expense_df = df[df['Type'] == 'Expense']
expense_df['Type'].unique()

array(['Expense'], dtype=object)

In [37]:
expense_df.groupby('Category')['Amount'].sum().sort_values(ascending=False)

Category
Travel              169497.79
Rent                162075.39
Food & Drink        159493.39
Salary              149053.55
Entertainment       148165.47
Shopping            146880.75
Utilities           146833.97
Health & Fitness    145194.06
Name: Amount, dtype: float64

In [38]:
expense_df.groupby('Category')['Type'].unique()

Category
Entertainment       [Expense]
Food & Drink        [Expense]
Health & Fitness    [Expense]
Rent                [Expense]
Salary              [Expense]
Shopping            [Expense]
Travel              [Expense]
Utilities           [Expense]
Name: Type, dtype: object

In [39]:
df.groupby('Category')['Type'].unique()

Category
Entertainment       [Expense]
Food & Drink        [Expense]
Health & Fitness    [Expense]
Investment           [Income]
Other                [Income]
Rent                [Expense]
Salary              [Expense]
Shopping            [Expense]
Travel              [Expense]
Utilities           [Expense]
Name: Type, dtype: object

In [43]:
salary_df = df[df['Category'] == 'Salary']
salary_df.head()
salary_df.tail()

           Date       Transaction Description Category   Amount     Type
1458 2024-11-13        Dinner rich decide do.   Salary  1950.21  Expense
1468 2024-11-19               Bit need allow.   Salary   606.22  Expense
1478 2024-11-25  Red republican father party.   Salary   383.70  Expense
1481 2024-11-30              Project at risk.   Salary  1456.94  Expense
1493 2024-12-21                 Up hear draw.   Salary   784.35  Expense

In [44]:
df.groupby(['Category', 'Type']).size()

Category          Type
Entertainment     Expense    143
Food & Drink      Expense    149
Health & Fitness  Expense    152
Investment        Income     142
Other             Income     136
Rent              Expense    165
Salary            Expense    146
Shopping          Expense    150
Travel            Expense    160
Utilities         Expense    157
dtype: int64

How many income and expense transactions are there in the dataset

In [47]:
df['Type'].value_counts()

Type
Expense    1222
Income      278
Name: count, dtype: int64

Inspecting Numericals Columns

In [48]:
df['Amount'].mean()

np.float64(1307.5209133333335)

In [49]:
df['Amount'].std()

np.float64(982.2833614507344)

In [50]:
df['Amount'].max()

np.float64(4996.0)

In [51]:
df['Amount'].min()

np.float64(14.37)

In [52]:
df['Amount'].count()

np.int64(1500)

In [53]:
df['Amount'].describe()

count    1500.000000
mean     1307.520913
std       982.283361
min        14.370000
25%       629.340000
50%      1156.285000
75%      1712.932500
max      4996.000000
Name: Amount, dtype: float64

In [54]:
df.groupby('Type')['Amount'].mean()

Type
Expense    1004.250712
Income     2640.600719
Name: Amount, dtype: float64

In [55]:
df.groupby('Type')['Amount'].describe()

,count,mean,std,min,25%,50%,75%,max
Type,,,,,,,,
Expense,1222.0,1004.250712,571.536986,14.37,516.8025,992.855,1484.9375,1999.82
Income,278.0,2640.600719,1261.890414,500.00,1531.7500,2655.000,3609.2500,4996.00

In [56]:
start_date = df['Date'].min()
print(start_date)

2020-01-02 00:00:00

In [57]:
end_date = df['Date'].max()
print(end_date)

2024-12-29 00:00:00

In [59]:
yearly_counts = df['Date'].dt.year.value_counts().sort_index()
print(yearly_counts)

Date
2020    290
2021    280
2022    303
2023    323
2024    304
Name: count, dtype: int64

Total Transaction amount in each year

In [64]:
df.groupby([df['Date'].dt.year, 'Type'])['Amount'].sum()

Date  Type
2020  Expense    255772.86
      Income     102266.00
2021  Expense    218644.46
      Income     150398.00
2022  Expense    256776.35
      Income     147726.00
2023  Expense    244498.24
      Income     160598.00
2024  Expense    251502.46
      Income     173099.00
Name: Amount, dtype: float64

yearly_summary is now a dataframe

In [67]:
yearly_summary = df.groupby([df['Date'].dt.year, 'Type'])['Amount'].sum().unstack()
print(yearly_summary)

Type    Expense    Income
Date
2020  255772.86  102266.0
2021  218644.46  150398.0
2022  256776.35  147726.0
2023  244498.24  160598.0
2024  251502.46  173099.0

In [68]:
yearly_summary['Savings'] = yearly_summary['Income'] - yearly_summary['Expense']
print(yearly_summary)

Type    Expense    Income    Savings
Date
2020  255772.86  102266.0 -153506.86
2021  218644.46  150398.0  -68246.46
2022  256776.35  147726.0 -109050.35
2023  244498.24  160598.0  -83900.24
2024  251502.46  173099.0  -78403.46

creating a copy of df to change salary from expense to income

In [73]:
clean_df = df.copy()
clean_df.loc[clean_df['Category'] == 'Salary', 'Type'] = 'Income'
clean_df.head()

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense

In [74]:
clean_df.groupby('Category')['Type'].unique()

Category
Entertainment       [Expense]
Food & Drink        [Expense]
Health & Fitness    [Expense]
Investment           [Income]
Other                [Income]
Rent                [Expense]
Salary               [Income]
Shopping            [Expense]
Travel              [Expense]
Utilities           [Expense]
Name: Type, dtype: object

In [80]:
clean_yearly_summary = clean_df.groupby([clean_df['Date'].dt.year, 'Type'])['Amount'].sum().unstack()

In [81]:
clean_yearly_summary

Type    Expense     Income
Date
2020  230296.73  127742.13
2021  194357.90  174684.56
2022  220761.52  183740.83
2023  217740.86  187355.38
2024  214983.81  209617.65

In [82]:
clean_yearly_summary['Savings'] = clean_yearly_summary['Income'] - clean_yearly_summary['Expense']
print(clean_yearly_summary)

Type    Expense     Income    Savings
Date
2020  230296.73  127742.13 -102554.60
2021  194357.90  174684.56  -19673.34
2022  220761.52  183740.83  -37020.69
2023  217740.86  187355.38  -30385.48
2024  214983.81  209617.65   -5366.16